name: image_text02
description: "new build of image_text"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <4.2.0"


dependencies:
  flutter_spinkit: 5.2.1
  path_provider: 2.1.5
  provider: 6.1.2
  percent_indicator: 4.2.4
  material_design_icons_flutter: 7.0.7296
  image: 4.5.3
  async: ^2.12.0
  http: 1.3.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  fonts:
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf
        - asset: fonts/Merriweather-Italic.ttf
          style: italic
        - asset: fonts/Merriweather-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
        - asset: fonts/DancingScript-Bold.ttf
          weight: 700


